### ISSUE TITLE
Run Test command from VSCode running Extremely slow.

### ISSUE THREAD

**Issue by 1ktribble** [forcedotcom/salesforcedx-vscode#1582]
### Summary

While attempting to run tests quickly from VSCode using the Apex extension using the button below, I am consistently getting extremely slow Command Times in comparison to the Test Execution Time.

<img width="467" alt="Screen Shot 2019-08-22 at 2 52 25 PM" src="https://user-images.githubusercontent.com/7140983/63541901-0dd70780-c4ed-11e9-8eef-6d8b54c8e909.png">

<img width="465" alt="Screen Shot 2019-08-22 at 2 57 14 PM" src="https://user-images.githubusercontent.com/7140983/63541982-3eb73c80-c4ed-11e9-96b9-a11b6b55bbed.png">

### Steps To Reproduce:

1. Create a test class and test method with @IsTest annotation.
2. Deploy test class into a sandbox.
3. Click 'Run Test' button in between test annotation and method signature.

### Expected result

I expect the test results to complete much faster than 2 minutes for a 136 ms test.

### Actual result

The test results completed in 2 minutes for a 136 ms test.

### Additional information

**VS Code Version**: 1.37.1

**SFDX CLI Version**: sfdx-cli/7.20.1

**OS and version**: macOS Mojave 10.14.6

**Comment by sc5148** [comment]
I am also facing this. Whenever  I am running tests it's taking 7-8 min on an average to get the test results. This is really bad.

**Comment by FischerMoseley** [comment]
I'm also having this issue when running the unit tests described in this [Trailhead](https://trailhead.salesforce.com/en/content/learn/modules/apex_testing/apex_testing_intro?trail_id=force_com_dev_beginner) module. I'm getting an execution time of 32ms, and a command time of 382096 ms.

I'm on Ubuntu 20.04 with OpenJDK 11 if that helps.

**Comment by D99000947** [comment]
I can also confirm having this issue.  It always takes **significantly** longer to get results back in VSCode by comparison.  I open the Developer Console, start the test in VSCode, then watch in the Developer Console as the test starts and completes, then wait several minutes before the command actually completes and returns any results in VSCode.

**Comment by juandomenechh** [comment]
Any updates on this? I am having the same problem. Apex test execution from VSCode takes a huge amount of time (9000ms aprox.) every time.

**Comment by lcampos** [comment]
Hi, we recently finished rewriting the Apex test commands. From the VSCode extension's side, we merged support for the new code this week (https://github.com/forcedotcom/salesforcedx-vscode/pull/2828) which will be available in the next release.

**Comment by ngoc-phan** [comment]
Having the same problem

**Comment by smaddox-sf** [comment]
Hi @ngoc-phan and All - This issue is solved in the Apex command library.  You can enable using that by checking the "Use Apex Library" setting in VS Code Settings:
![image](https://user-images.githubusercontent.com/59572234/108427421-01bb2b80-71f2-11eb-9d12-c47618a13955.png)

Give it a try and let us know if you still see issues. 

For context about this setting, we are in the process of restructuring commands to use a library, whether called from the CLI or VS Code extensions.  The first step is build the library and give you an option to use it through the setting.  It will soon be the default in VS Code and we're in the process of updating the CLI as well.

**Comment by ViktorBakanov** [comment]
@smaddox-sf Hi!

This feature not exists in vscode settings, and it seems like we issue is not fixed completely.
