### ISSUE TITLE
Unable to Create Project in VS Code due to 'Salesforce CLI Integration' extension taking too long and preventing others extensions from opening

### ISSUE THREAD

**Issue by adaslal** [forcedotcom/salesforcedx-vscode#2295]
### Summary

Unable to Create Project in VS Code due to 'Salesforce CLI Integration' extension taking too long and preventing others extensions from opening.

I have installed SFDX CLI and VS Code with the 'Salesforce Extension Pack'. Even then,I am not able to create a Salesforce Project in VS code

### Steps To Reproduce:

1.  Open VS Code
2.  Press Ctrl + Shift + P.
3.  Select 'Create SFDX Project'

### Expected result

You should be prompted to Select between types of Project(Eg: 'Standard')

### Actual result

I see the notification 'Activating Extensions' at the bottom left and nothing happens afterwards. When I checked the Issue I saw the following which says

'Did you attach the CPU Profile'

'This is a reminder to make sure that you have not forgotten to attach 'C:\Users\myName\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt' to an existing performance issue.
![image](https://user-images.githubusercontent.com/57103745/85872379-45899c80-b7ed-11ea-8dd6-6d8df85af0ec.png)

### Additional information

_Feel free to attach a screenshot_.
![image](https://user-images.githubusercontent.com/57103745/85872866-fabc5480-b7ed-11ea-9460-bdc2df0989be.png)

**VS Code Version**: 
Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**SFDX CLI Version**: sfdx-cli/7.63.0-c897e8bb1a win32-x64 node-v10.20.1

**OS and version**:  OS - Windows 10 Enterprise. Version - 1909

**Comment by smaddox-sf** [comment]
Hi @adaslal - Thanks for reaching out.  It sounds like the CLI setup might not be quite right.  That is usually the case when you see the 'activating' message but nothing happens.  Can you verify if the CLI configuration is [setup as described here](https://developer.salesforce.com/tools/vscode/en/troubleshooting/#set-salesforce-cli-path-windows)?

**Comment by adaslal** [comment]
@smaddox-sf  I think the Salesforce CLI is installed correctly
![image](https://user-images.githubusercontent.com/57103745/86154943-5dc92680-bb21-11ea-8512-ffab6795c49c.png)

However,I am able to work on LWC as I had downgraded some components of Salesforce Extension Pack as shown below
![image](https://user-images.githubusercontent.com/57103745/86155275-cfa17000-bb21-11ea-93c0-5fbeee44b133.png)

The main issue that I noticed after downgrading the above components was that 'Salesforce CLI Integration' extension was taking too long to complete. I also noticed that,even though the operation was completed, I don't see the Completion message.

The latest edition of 'Salesforce Extension Pack' had problems especially 'Salesforce CLI Integration'

**Comment by brpowell** [comment]
@adaslal Your setup looks all good, would you mind attaching that CPU profile the message prompted you with to this thread? We can take a closer look as to what's going on.

**Comment by adaslal** [comment]
@brpowell you can find the CPU Profile error file attached 
[CPU Profile Error.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/4858593/CPU.Profile.Error.txt)

I would like to point out that the CPU error did not show up again.

**Comment by lcampos** [comment]
@adaslal we released some changes in version 48.24.0 that speed up the activation of the extensions. We're working on follow up enhancements but let us know if your experience got a bit better now.

**Comment by Rakhi22** [comment]
I am having the same issue and have installed latest  version 48.24.0 but it did not work, still getting the same issue.
Tried installing downgraded versions but no luck.

**Comment by adaslal** [comment]
@Rakhi22  You can try downgrading two specific extensions namely 'Salesforce CLI Integration' and 'Lightning Web Components' to v48.17.0 while other extensions which are part of Salesforce extension pack can be upgraded to latest. I noticed that it worked for me

![Uploading image.png…]()

**Comment by Rakhi22** [comment]
@adaslal I tried what you instructed but did not work.

**Comment by Rakhi22** [comment]
I tried running Salesforce CLI commands to create new project and authorize an org through command prompt, it is working. But when i'm trying to do same through Visual Studio Code, i'm getting following error -
![image](https://user-images.githubusercontent.com/59822255/87569500-d7960e00-c6e4-11ea-9663-78b8e499f804.png)

**Comment by lcampos** [comment]
In the last months we've been releasing updates to the extensions to address this issue. Updating to the latest version of the extensions (currently v51.2.0) should allow you to run the project scaffold commands.

**Comment by toufikat** [comment]
hello
Still having this issue even with latest updates... sfdx extensions are terribly slow on startup

Version : 
`sfdx-cli/7.155.1 win32-x64 node-v16.15.1
`
Log output
`[2022-07-19 12:21:05.022] [renderer1] [warning] UNRESPONSIVE extension host: 'salesforce.salesforcedx-vscode-apex' took 99% of 5404.922ms, saved PROFILE here: 'file:///~/AppData/Local/Temp/exthost-8ade88.cpuprofile' [{"id":"gc","total":28641,"percentage":1},{"id":"salesforce.salesforcedx-vscode-apex","total":5374739,"percentage":99}]
`

**Comment by jayvee-miranda** [comment]
still encountering this issue, is there already fix for this?

**Comment by aanshkumar** [comment]
hey i am also facing thr same issue, has anyone got any solution, please help me out

**Comment by maygemSFSD** [comment]
Having this same issue - checked the CLI configuration, tried deleting and redownloading extension packs, etc. Still cannot create a new project.

**Comment by FirelinkSolutions** [comment]
Having the same issue. Can someone help ?
