### ISSUE TITLE
Unable to create Project since Running: SFDX Create Project runs forever

### ISSUE THREAD

**Issue by ParulDua** [forcedotcom/salesforcedx-vscode#2385]
![image](https://user-images.githubusercontent.com/66628966/88918789-ae01e880-d287-11ea-8b72-0cb24a284798.png)

Hi Team,

When I try to create a Project with Manifest, the command keeps running. No project gets created even after almost half an hour (max I have waited before cancelling the operation). Kindly help.

VS Code Version: 1.47.3 (user setup)

SFDX CLI Version: sfdx-cli/7.63.0-c897e8bb1a win32-x64 node-v10.20.1

OS and version: Windows 10 Pro and 10.0.18363

**Comment by lcampos** [comment]
This could be a problem with the way you've configured the Salesforce CLI in your machine. Can you confirm the configuration shown in [Set Salesforce CLI path Windows](https://developer.salesforce.com/tools/vscode/en/troubleshooting/#set-salesforce-cli-path-windows) is present in your machine ?

**Comment by ParulDua** [comment]
Yes I have re confirmed the settings as per the link provided. They are in place already.

**Comment by jpoonam4** [comment]
Sfdx: Create Project  keeps on running until I don't cancel that.
And folder gets created on system but it don't open in VSC Or Vsc do not reload with project which I have created.
The popup of command keeps on running. And there is no ouput which ends with words as:
**ended with exit code  0.**

**Comment by smaddox-sf** [comment]
Can you both try updating to the latest CLI version and let us know whether that has resolved the issue? (In case you need info on how to update: Use `sfdx update` command in the terminal.)

**Comment by jpoonam4** [comment]
Run on terminal SFDX Update. For updating CLI version It haven't resolved the issue. Need help Facing issue it is being long time.

**Comment by jpoonam4** [comment]
from terminal run SFDX update . But it haven't solved the issue.

**Comment by lcampos** [comment]
@jpoonam4 yesterday we released a fix as part of version 49.8.0 of the extension that addresses this. Can you make sure you are on the latest version of the extension ?

**Comment by lcampos** [comment]
Closing since the fix was released in version 49.8.0

**Comment by jpoonam4** [comment]
Thanks  Sfdx: Create Project is working fine in  version 49.8.0 
But SFDX: Deploy Source to Org , SFDX: Authorize an Org still have issue
