### ISSUE TITLE
Error message when VS Code is loading without SFDX project

### ISSUE THREAD

**Issue by Shababsoft** [forcedotcom/salesforcedx-vscode#3111]
When I open non-sfdx project folder in vscode I am getting the following error message

"!!! MISSING LABEL !!! predicates_no_sfdx_project_found_text"

### Steps To Reproduce:

1.  Open a non-sfdx project in vscode
1.  You will see an error notification window

### Expected result

I should not be seeing any error message if the opened folder is not SFDX project folder.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.55

**SFDX CLI Version**: 7.90.2

**OS and version**: Mac OS Big Sur

### Screenshots:

<img width="480" alt="image" src="https://user-images.githubusercontent.com/4686730/113294228-a1d69b00-92ee-11eb-9565-16e5741a3652.png">

**Comment by apexkeen** [comment]
I also get same error and it is coming with sfdx project.  Because of this, I've to 'type' everything while coding

**Comment by smaddox-sf** [comment]
Thanks for reporting this @Shababsoft and @apexkeen .  We're working on a fix

**Comment by peternoges** [comment]
btw, a **temporary** workaround for me was to downgrade to an earlier version,   such as `sfdx plugins:install salesforcedx@51.5.0`

**Comment by pooja-kudale** [comment]
facing the issue while trying to SFDX:retrieve source in manifest from org in vs code 
Vs code version is : 1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
x64

OS : Win 10

![Vs Error](https://user-images.githubusercontent.com/95013641/147729102-1852a165-65c2-4457-ace3-3f655e635e48.png)

**Comment by AnanyaJha** [comment]
Hi @pooja-kudale thanks for raising your issue! Can you share what version of the Salesforce Extensions you're using? This can be found by clicking on the Marketplace icon on the left hand side and searching for Salesforce. The version will be listed on the Extension homepage.

**Comment by pooja-kudale** [comment]
@AnanyaJha  it's v53.12.0

**Comment by mohanraj-r** [comment]
@pooja-kudale @Shababsoft This issue should be fixed now. If not please re-open the issue with details.

**Comment by dipankarsahoo180** [comment]
I'm still facing this issue with latest cli. !!! MISSING LABEL !!! predicates_no_sfdx_project_found_text

**Comment by AngelMtz97** [comment]
![image](https://user-images.githubusercontent.com/51268614/165683335-9465136d-904d-4d91-b025-ae29a0eed3fb.png)
![image](https://user-images.githubusercontent.com/51268614/165683389-0630bc89-a631-478f-ad33-6e641af789e1.png)

Please help with this error

**Comment by IVerkhosh** [comment]
Hello,
I am facing the same issue after updating to sfdx-cli/7.151.1 win32-x64 node-v16.15.0

**Comment by jeffb-sfdc** [comment]
@IVerkhosh your issue with not being able to authorizer an org does not seem to be the same issue as the one that's here, in the ticket.  Pleas open a new ticket so we can track the issue with not being able to authorize a new org.

**Comment by jeffb-sfdc** [comment]
@dipankarsahoo180 I am not able to reproduce the issue, and the issue seems fixed.  To reproduce the issue I performed the following tests:

Test 1-empty folder
OS: Mac OS X 12
1. In the Finder, I created a new folder, named `empty_folder`
2. I ran VS Code (1.68.0) along with the Salesforce Extension pack for VS Code (55.0.0) installed
3. Selected menu File > Open
4. Navigated to where `empty_folder` was, and then clicked the Open button
Result: I did not see "!!! MISSING LABEL !!! predicates_no_sfdx_project_found_text" appear


Test2-newly created React app
OS: Mac OS X 12
1. Opened a terminal and ran `npx create-react-app sample-react-app"
2. After the project was created, I ran VS Code (1.68.0) along with the Salesforce Extension pack for VS Code (55.0.0) installed
3. Selected menu File > Open
4. Navigated to where the source code for the react app was at, and then clicked the Open button
Result: I did not see "!!! MISSING LABEL !!! predicates_no_sfdx_project_found_text" appear

I am going to close this ticket.  If you are able to reproduce this, please provide step-by-step instructions with the steps you are performing.  Also, please post on GitHub a copy of the source you are opening - perhaps there's a file or a file structure that causes this bug to happen.
