### ISSUE TITLE
Apex Replay Debugger VS Code: Unverified Break point

### ISSUE THREAD

**Issue by smudivartysitetracker** [forcedotcom/salesforcedx-vscode#3267]
### Summary

Hi Everyone,
I am experiencing an issue with the Apex Replay Debugger on my Mac. When I am trying to replay a log file in Apex Replay Debugger in VSCode, the debugger never stops at the specified break point.
When I hover over the breakpoint when the log file execution starts, it shows the breakpoint as an ‘unverified breakpoint’.
I have verified the logs and it didn't skip any bytes during the execution which could potentially prevent the debugger from stopping at the break point.
I have specified the Salesforcedx-vscode-apex › Java: Home in the settings as well.
Is there something that I am missing ?
Here is the configuration for the Apex Replay Debugger
{
"version": "0.2.0",
"configurations": [
{
"name": "Launch Apex Replay Debugger",
"type": "apex-replay",
"request": "launch",
"logFile": "${command:AskForLogFileName}",
"stopOnEntry": true,
"trace": true
},
{
"name": "Launch Apex Debugger",
"type": "apex",
"request": "launch",
"sfdxProject": "${workspaceRoot}"
}
]
}
Any help is greatly appreciated.
Thanks,
Uday

### Steps To Reproduce:

1.  Get Apex Debug Logs
2.  Select Breakpoints in your class
3.  Right click on the log 
4.  Click on Launch Apex Replay Debugger

### Expected result

Stop at the selected breakpoint

### Actual result

Never stops at the specified breakpoint even when the condition is met and it shows the breakpoint as unverified breakpoint

### Additional information

![Screen Shot 2021-05-21 at 12 28 26 PM](https://user-images.githubusercontent.com/84805631/119574776-d3a63400-bd6a-11eb-9176-509db3097e1d.jpg)

![image](https://user-images.githubusercontent.com/84805631/119574883-fafd0100-bd6a-11eb-9b99-c85b6a9411ca.png)

![image](https://user-images.githubusercontent.com/84805631/119575550-16b4d700-bd6c-11eb-8cb9-195a5bce3a86.png)

**VS Code Version**:
Version: 1.56.2 (Universal)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z (1 wk ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.4.0

**SFDX CLI Version**:
sfdx-cli/7.102.0 darwin-x64 node-v16.1.0

**OS and version**:
macOS Big Sur Version 11.3.1

**Comment by smudivartysitetracker** [comment]
@lcampos 
Any help on this issue is really appreciated !!!

**Comment by xyc** [comment]
@smudivartysitetracker does this thread apply to your situation https://github.com/forcedotcom/salesforcedx-vscode/issues/1563#issuecomment-526422242?

**Comment by smudivartysitetracker** [comment]
No it doesn't relate to my situation.

**Comment by bmosca** [comment]
I am also experiencing this issue when I debug. 
Breakpoints seems to be ignored even though when hitting the "Debug Single Test" under Testing tab which used to work a few weeks back.

![image](https://user-images.githubusercontent.com/1205040/121501395-1d338780-c9d7-11eb-8fa4-4ef47df29bc1.png)

**Comment by smudivartysitetracker** [comment]
@bmosca any luck in figuring out, if there was a way to fix the issue?
I am still facing the same issue

**Comment by bmosca** [comment]
@smudivartysitetracker this seems to have been fixed with the update this morning, debugging now stops on my defined breakpoints.
Update the plugin and give it a go

**Comment by rcoringrato-sfdc** [comment]
@smudivartysitetracker Is this still an issue for you? Make sure your project files are in sync with your org files before attempting to debug.

**Comment by smudivartysitetracker** [comment]
Hi @rcoringrato-sfdc,
I used the sfdx force:source:push before running the test classes and the org has all the file updated. This issue is still happening on my scratch orgs.

**Comment by randi274** [comment]
Just checking in on this issue as it's been a few months now; is this still a problem for you @smudivartysitetracker?

**Comment by smudivartysitetracker** [comment]
Hi @randi274,
I am still running into the same issue. I tried to sync all the files before I attempted to debug, but still no luck. Any support would be really appreciated.

**Comment by gbockus-sf** [comment]
Hi @smudivartysitetracker Sorry for the run around on this issue.  In the last few releases we've done a lot of work to make the replay debugger configuration and use simpler.  Just wanted to verify you are still see this.  If it is still an issue could you send you latest SFDX, VSCode, and OS info (or update the description).  Thanks!
