### ISSUE TITLE
"Cannot read property 'fspath' of undefined" when executing "Deploy This Source" action

### ISSUE THREAD

**Issue by achere** [forcedotcom/salesforcedx-vscode#3656]
### Summary

When I try to run "Deploy This Source" action, I get an error "Cannot read property 'fspath' of undefined". Previously this feature worked fine

### Steps To Reproduce:

1.  Authorize an org
1.  Open valid source file in the editor (Apex class, LWC, etc.)
1.  Execute action "SFDX: Deploy This Source To Org"

### Expected result

Source deployed to target Org

### Actual result

Got an error: "Command 'SFDX: Deploy This Source to Org' resulted in an error (Cannot read property 'fsPath' of undefined)"

### Additional information

<img width="544" alt="Screenshot 2021-11-18 at 18 51 19" src="https://user-images.githubusercontent.com/7329670/142452649-8fe54cfc-6d37-440f-8888-669d8bd758d0.png">
<img width="425" alt="Screenshot 2021-11-18 at 19 08 51" src="https://user-images.githubusercontent.com/7329670/142452668-d1782fe7-6471-466a-ae68-ed6246f3cc11.png">

I can also see errors like "[Extension Host] (node:34190) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency" in the VSCode console, referencing various *nix commands (cat, cd, chmod, cp). Not sure if this is related, but I don't get them while opening non-SF projects.
I tried reinstalling extensions, VSCode, node, but to no avail. This feature did work previously on this machine, and I can't pinpoint what could've caused it

**Salesforce Extension Version in VS Code**:

v53.4.0

**SFDX CLI Version**:

sfdx-cli/7.123.0 darwin-x64 node-v14.18.1

**OS and version**:
macOS Mojave 10.14.5 (18F132)

**Comment by randi274** [comment]
Hi @achere, what kind of org are you deploying to?

**Comment by ArtsiomT** [comment]
> Hi @achere, what kind of org are you deploying to?

Not OP, but today I faced the same issue with deployment to a sandbox. Was trying to downgrade the extension pack to the prev version but the error still.

**Comment by achere** [comment]
> Hi @achere, what kind of org are you deploying to?

Hi @randi274! Full copy sandbox.

**Comment by scanlan111** [comment]
This just happened today, I was able to use a keyboard shortcut to deploy all day yesterday and now when using the shortcut I am getting the 'Cannot read property 'fsPath' of undefined' alert.

Right clicking and using Deploy from menu works but i'd rather my shortcut work.

**Comment by johndturn** [comment]
I'm currently running into this while attempting to retrieve metadata from a Dev sandbox as well.

**Comment by biwashingtonial** [comment]
Can confirm exactly what OP and commenters describe. Just started today. The type of connected org seems not to matter.

**Comment by tchorsch** [comment]
This is also impacting me in orgs that worked fine yesterday. Can confirm for me as well that right click to deploy seems to still work.

**Comment by tchorsch** [comment]
After speaking with a colleague, for me at least, I found that my sfdx extension had updated and was in "Reload Required". Reloading the extension resolved the issue.

**Comment by randi274** [comment]
We shipped a patch release yesterday to resolve this, so with a reload of the extensions this should be resolved for everyone. Thanks for the patience and comments all!

**Comment by 8bit-cutie** [comment]
Still experiencing this issue, I verified that everything is up to date (SF CLI, vscode, etc)
