### ISSUE TITLE
Installing the Apex Prettier Plugin using npm throws an error.

### ISSUE THREAD

**Issue by kaustubhdapurkar** [forcedotcom/salesforcedx-vscode#3863]
### Summary

NPM throws error while installing prettier using the `npm install --save-dev --save-exact prettier prettier-plugin-apex` in a new SFDX project.

### Steps To Reproduce:

1.  Create a new project with manifest.
2. Run the `npm install --save-dev --save-exact prettier prettier-plugin-apex` command in the terminal.

### Expected result

The prettier module for apex should get installed successfully.

### Actual result

Running the command throws an error.

### Additional information

![image](https://user-images.githubusercontent.com/48684659/155834013-abf4085a-10bf-428d-b249-18513ece3759.png)

### Workaround I do to fix this

To fix this, I navigate to the package.json file in the project and change the `prettier-plugin-apex` version from 1.10.1 to 1.10.0 and run the npm command again and the command runs successfully.

**Salesforce Extension Version in VS Code**: Salesforce Extension Pack (Expanded)
v54.2.0

**SFDX CLI Version**: sfdx-cli/7.137.1 win32-x64 node-v16.13.2

**OS and version**: Windows 11 Version 10.0.22000.493

**Comment by randi274** [comment]
Thanks for reporting this! We've fixed this in our [templates](https://github.com/forcedotcom/salesforcedx-templates/issues/394) library, and once we update that (which is a WIP), this should be fixed as well.

**Comment by mohanraj-r** [comment]
@kaustubhdapurkar This should be fixed now with the recent update. Please check and reopen this issue with details if it is still not resolved.

**Comment by vamsisfdev** [comment]
Hello, I am still having the error with using the same 

![Image](https://github.com/user-attachments/assets/01e8fd47-9ecb-438b-a1f1-395de0c8082f)
