### ISSUE TITLE
ContractStatus standard value set can't be pushed if customized

### ISSUE THREAD

**Issue by gdoenlen** [forcedotcom/salesforcedx-vscode#785]
### Summary
When you customize the contract status field you cannot push it into a scratch org you receive the error: 

`Field: null is not a picklist`

### Steps To Reproduce:

1.  Create a new scratch org
2.  Add a new custom value for the Contract Status picklist
3. run `sfdx force:source:pull` to get the `ContractStatus.standardValueSet-meta.xml` file
4. Create another new scratch org
5. run `sfdx force:source:push` and receive the above error for the standard value set.

### Expected result

The customized standard value set should have been pushed into the scratch org.

### Actual result

You receive an error claiming that null is not a picklist.

**VS Code Version**:
1.29.1
**SFDX CLI Version**:
sfdx-cli/6.42.0-ae478b3cb8 (linux-x64)
**OS and version**:
I've tried on both linux (ubuntu budgie 18.04) and windows 10

**Comment by gdoenlen** [comment]
@ntotten is there any update on this or #797 ? Are they slotted internally to be fixed? These are HUGE blockers for my current projects workflow in DX.

**Comment by ntotten** [comment]
I am reaching out to the Metadata API team and will follow up. These are not bugs in VS Code, but rather on the core service so it will unfortunately not be something that is fixed in a matter of weeks. I will see when they may have the work scheduled.

**Comment by gdoenlen** [comment]
Thank you, I really appreciate that. 

I understand that this repo is only for the VS Code extensions, but I'm afraid that my only other course of action is salesforce support and that would never provide me with a solution.

Is there a better way for me to report such bugs around the MDAPI or the CLI itself?

**Comment by ntotten** [comment]
No worries, posting here is fine. We are still trying to figure out how/if we might use github for things that are not open source like the MDAPI.

**Comment by gdoenlen** [comment]
Ok, Thanks! [Valve](https://github.com/ValveSoftware) does something similar for their closed sourced software.

**Comment by ntotten** [comment]
I have asked the team about this issue. They have it recorded as a known bug and will be working on fixing it. I don't have a timeline to share though. I am going to close this issue here as it is unrelated to VS Code.

**Comment by FabienTaillon** [comment]
Looks like this one is fixed, I was able to retrieve and deploy ContractStatus StandardValueSet without error. `groupingString` is now part of the metadata file.

**Comment by oalexandrino** [comment]
It appears to not be fixed.

I am still getting this issue

`force-app/main/default/standardValueSets/ContractStatus.standardValueSet-meta.xml  field integrity exception: unknown (invalid value)`

to solve? I had to delete manually some picklist items before deploying...

**Comment by arafesthain** [comment]
same issue here

Error  ContractStatus  field integrity exception: unknown (invalid value)

**Comment by FabienTaillon** [comment]
I tried again and I don't have the issue, are you running the latest CLI version and using latest API version ?
From a new scratch org, do you have exact steps to reproduce the issue ?

**Comment by jh480** [comment]
This is again an error in the mdapi, it will not go through the sfdx team.

All you can do is create a case with SF, get told it's working as designed and to post an idea about it.

**Comment by jh480** [comment]
@pinkj24, I could resolve this by setting the API values on the target org to ones of those that exist in the deployment. Apparently, Contract.Status cannot have inactive values.

**Comment by fabioderosaEF** [comment]
> @pinkj24, I could resolve this by setting the API values on the target org to ones that exist in the deployment. Apparently, Contract.Status cannot have inactive values.

I confirm the above works fine. Values existing at destination needs to be in the source org. As I am using record types, I have just excluded the values not needed in the RT metadata.
